name: Open a new issue

on: workflow_dispatch

jobs:
  open-new-issue:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Create issue
        run: |
          gh issue create \
            --repo ${{ github.repository }} \
            --title "Test issue from workflow" \
            --body "This issue was created by GitHub Actions"
        env:
          GH_TOKEN: ${{ github.token }}
